init:
    path:       /secretinitialization/
    methods:    [GET]
    defaults:   { _controller: LifeLabRestBundle:Init:index }

rest_routing:
    type:       rest
    resource:   "@LifeLabRestBundle/Resources/config/routing/rest_routing.yml"

fos_user:
    resource:   "@FOSUserBundle/Resources/config/routing/all.xml"